AWSTemplateFormatVersion: '2010-09-09'
Description: 'URL Redirector microservice - Base deployment'

Parameters:
  FunctionRuntime:
    Type: String
    Default: nodejs6.10
  FunctionTimeout:
    Type: Number
    Default: 180

Resources:
  RestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Body:
        $ref: 'swagger.yaml'
      EndpointConfiguration:
        Types:
          - REGIONAL

  RestApiLatestDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      Description:
        $ref: 'swagger.yaml#/info/version'
      RestApiId:
        Ref: RestApi
      StageName: 'latest'

  RedirectHandler:
    Type: 'AWS::Lambda::Function'
    DependsOn: RedirectHandlerRole
    Properties:
      Handler: index.handler
      Code: ./
      Role:
        'Fn::GetAtt':
          - RedirectHandlerRole
          - Arn
      Runtime:
        Ref: FunctionRuntime
      Timeout:
        Ref: FunctionTimeout

  RedirectHandlerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        -
          PolicyName: 'root'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: 'Allow'
                Action: '*'
                Resource: '*'

  RedirectHandlerRestApiPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: RedirectHandler
      Principal: 'apigateway.amazonaws.com'

Outputs:
  RestApiIdOutput:
    Description: 'The ID of the API resource.'
    Value:
      Ref: RestApi
    Export:
      Name:
        'Fn::Join':
          - ":"
          -
            - Ref: 'AWS::StackName'
            - RestApiId
