AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Helloworld microservice - Initialization.'
Globals:
  Function:
    Runtime: nodejs6.10
    Timeout: 180
Resources:
  RestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Body: 
        $ref: 'swagger.yaml'
  HelloworldHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      CodeUri: ./
      Events:
        Request:
          Type: Api
          Properties:
            Path: /helloworld/
            Method: any
            RestApiId: 
              Ref: RestApi
    DependsOn:
      - RestApi
  LatestBuildDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      Description:
        $ref: 'swagger.yaml#/info/version'
      RestApiId:
        Ref: RestApi
      StageDescription: 'The latest build.'
      StageName: 'latest-build'
    DependsOn:
      - RestApi
      - HelloworldHandler
Outputs:
  ApiIdOutput:
    Description: 'The ID of the API resource.'
    Value: 
      Ref: RestApi
    Export:
      Name:
        'Fn::Join':
          - ":"
          -
            - Ref: "AWS::StackName"
            - RestApiId
