AWSTemplateFormatVersion: '2010-09-09'
Description: 'Helloworld microservice - Initialization.'
Parameters:
  FunctionRuntime:
    Type: String
    Default: nodejs6.10
  FunctionTimeout:
    Type: Number
    Default: 180
Resources:
  RestApi:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Body:
        $ref: 'swagger.yaml'

  RestApiLatestDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      Description:
        $ref: 'swagger.yaml#/info/version'
      RestApiId:
        Ref: RestApi
      StageDescription:
        Description: 'Latest version.'
      StageName: 'latest'

  HelloworldHandler:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: index.handler
      Code:
        ZipFile: ./
      Role:
        'Fn::GetAtt':
          - HelloworldHandlerRole
          - Arn
      Runtime:
        Ref: FunctionRuntime
      Timeout:
        Ref: FunctionTimeout

  HelloworldHandlerRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
      Policies:
        -
          PolicyName: 'root'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: 'Allow'
                Action: '*'
                Resource: '*'

  HelloworldHandlerRestApiPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        Ref: HelloworldHandler
      Principal: 'apigateway.amazonaws.com'

Outputs:
  RestApiIdOutput:
    Description: 'The ID of the API resource.'
    Value:
      Ref: RestApi
    Export:
      Name:
        'Fn::Join':
          - ":"
          -
            - $ref: 'package.json#/config/StackName'
            - RestApiId
