AWSTemplateFormatVersion: '2010-09-09'
Description: 'Helloworld microservice - Configuration.'
Parameters:
  StageNameParameter:
    Type: String
    Default: V1
    Description: 'An identifier used to differentiate resources across deployments.'
  StageDescriptionParameter:
    Type: String
    Default: ''
    Description: 'A description of this specific deployment.'
Resources:
  EndpointsDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      Description:
        $ref: 'swagger.yaml#/info/version'
      RestApiId:
        'Fn::ImportValue':
          'Fn::Join':
            - ":"
            -
              - $ref: 'swagger.yaml#/x-baseStackName'
              - RestApiId
      StageDescription:
        Description:
          Ref: StageDescriptionParameter
      StageName:
        Ref: StageNameParameter
