AWSTemplateFormatVersion: '2010-09-09'
Description: 'URL Redirector microservice - Stage deployment'
Parameters:
  BaseStackName:
    Type: String
    Description: 'The name of the stack that houses the RestApi base.'
  StageNameParameter:
    Type: String
    Default: V1
    Description: 'An identifier used to differentiate resources across deployments.'
Resources:
  EndpointsDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      Description:
        $ref: 'swagger.yaml#/info/version'
      RestApiId:
        'Fn::ImportValue':
          'Fn::Join':
            - ':'
            -
              - Ref: BaseStackName
              - RestApiId
      StageName:
        Ref: StageNameParameter
  EndpointsDeploymentStage:
    Type: 'AWS::ApiGateway::Stage'
    DependsOn:
      - EndpointsDeployment
      - RedirectsTable
    Properties:
      DeploymentId:
        Ref: EndpointsDeployment
      RestApiId:
        'Fn::ImportValue':
          'Fn::Join':
            - ':'
            -
              - Ref: BaseStackName
              - RestApiId
      StageName:
        Ref: StageNameParameter
      Variables:
        redirectsTableName:
          Ref: RedirectsTable
  RedirectsTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName:
        'Fn::Join':
          - '.'
          -
            - Ref: BaseStackName
            - Ref: StageNameParameter
            - 'redirects'
      AttributeDefinitions:
        -
          AttributeName: 'id'
          AttributeType: 'S'
      KeySchema:
        -
          AttributeName: 'id'
          KeyType: 'HASH'
      ProvisionedThroughput:
        ReadCapacityUnits: '1'
        WriteCapacityUnits: '1'
