AWSTemplateFormatVersion: '2010-09-09'
Description: 'Helloworld microservice - Stage.'
Parameters:
  BaseStackName:
    Type: String
    Description: 'The name of the stack that houses the RestApi base.'
  StageNameParameter:
    Type: String
    Default: V1
    Description: 'An identifier used to differentiate resources across deployments.'
Resources:
  EndpointsDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    Properties:
      Description:
        $ref: 'swagger.yaml#/info/version'
      RestApiId:
        'Fn::ImportValue':
          'Fn::Join':
            - ":"
            -
              - Ref: BaseStackName
              - RestApiId
      StageName:
        Ref: StageNameParameter
